/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppGigsRouteImport } from './routes/_app.gigs'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppChatIndexRouteImport } from './routes/_app.chat.index'
import { Route as AppRoomsMineRouteImport } from './routes/_app.rooms.mine'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app.notes.$noteId'
import { Route as AppLecturesLectureIdRouteImport } from './routes/_app.lectures.$lectureId'
import { Route as AppFeedAdminRouteImport } from './routes/_app.feed.admin'
import { Route as AppFeedPostIdRouteImport } from './routes/_app.feed.$postId'
import { Route as AppChatRoomIdRouteImport } from './routes/_app.chat.$roomId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsRoute = AppGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsMineRoute = AppRoomsMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => AppRoomsRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppLecturesLectureIdRoute = AppLecturesLectureIdRouteImport.update({
  id: '/lectures/$lectureId',
  path: '/lectures/$lectureId',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedAdminRoute = AppFeedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppFeedRoute,
} as any)
const AppFeedPostIdRoute = AppFeedPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AppFeedRoute,
} as any)
const AppChatRoomIdRoute = AppChatRoomIdRouteImport.update({
  id: '/chat/$roomId',
  path: '/chat/$roomId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/gigs': typeof AppGigsRoute
  '/home': typeof AppHomeRoute
  '/notes': typeof AppNotesRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/rooms': typeof AppRoomsRouteWithChildren
  '/chat/$roomId': typeof AppChatRoomIdRoute
  '/feed/$postId': typeof AppFeedPostIdRoute
  '/feed/admin': typeof AppFeedAdminRoute
  '/lectures/$lectureId': typeof AppLecturesLectureIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/rooms/mine': typeof AppRoomsMineRoute
  '/chat/': typeof AppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/gigs': typeof AppGigsRoute
  '/home': typeof AppHomeRoute
  '/notes': typeof AppNotesRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/rooms': typeof AppRoomsRouteWithChildren
  '/chat/$roomId': typeof AppChatRoomIdRoute
  '/feed/$postId': typeof AppFeedPostIdRoute
  '/feed/admin': typeof AppFeedAdminRoute
  '/lectures/$lectureId': typeof AppLecturesLectureIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/rooms/mine': typeof AppRoomsMineRoute
  '/chat': typeof AppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/feed': typeof AppFeedRouteWithChildren
  '/_app/gigs': typeof AppGigsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/notes': typeof AppNotesRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/rooms': typeof AppRoomsRouteWithChildren
  '/_app/chat/$roomId': typeof AppChatRoomIdRoute
  '/_app/feed/$postId': typeof AppFeedPostIdRoute
  '/_app/feed/admin': typeof AppFeedAdminRoute
  '/_app/lectures/$lectureId': typeof AppLecturesLectureIdRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_app/rooms/mine': typeof AppRoomsMineRoute
  '/_app/chat/': typeof AppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/feed'
    | '/gigs'
    | '/home'
    | '/notes'
    | '/profile'
    | '/rooms'
    | '/chat/$roomId'
    | '/feed/$postId'
    | '/feed/admin'
    | '/lectures/$lectureId'
    | '/notes/$noteId'
    | '/rooms/mine'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/feed'
    | '/gigs'
    | '/home'
    | '/notes'
    | '/profile'
    | '/rooms'
    | '/chat/$roomId'
    | '/feed/$postId'
    | '/feed/admin'
    | '/lectures/$lectureId'
    | '/notes/$noteId'
    | '/rooms/mine'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/feed'
    | '/_app/gigs'
    | '/_app/home'
    | '/_app/notes'
    | '/_app/profile'
    | '/_app/rooms'
    | '/_app/chat/$roomId'
    | '/_app/feed/$postId'
    | '/_app/feed/admin'
    | '/_app/lectures/$lectureId'
    | '/_app/notes/$noteId'
    | '/_app/rooms/mine'
    | '/_app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs': {
      id: '/_app/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof AppGigsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms/mine': {
      id: '/_app/rooms/mine'
      path: '/mine'
      fullPath: '/rooms/mine'
      preLoaderRoute: typeof AppRoomsMineRouteImport
      parentRoute: typeof AppRoomsRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/_app/lectures/$lectureId': {
      id: '/_app/lectures/$lectureId'
      path: '/lectures/$lectureId'
      fullPath: '/lectures/$lectureId'
      preLoaderRoute: typeof AppLecturesLectureIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed/admin': {
      id: '/_app/feed/admin'
      path: '/admin'
      fullPath: '/feed/admin'
      preLoaderRoute: typeof AppFeedAdminRouteImport
      parentRoute: typeof AppFeedRoute
    }
    '/_app/feed/$postId': {
      id: '/_app/feed/$postId'
      path: '/$postId'
      fullPath: '/feed/$postId'
      preLoaderRoute: typeof AppFeedPostIdRouteImport
      parentRoute: typeof AppFeedRoute
    }
    '/_app/chat/$roomId': {
      id: '/_app/chat/$roomId'
      path: '/chat/$roomId'
      fullPath: '/chat/$roomId'
      preLoaderRoute: typeof AppChatRoomIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppFeedRouteChildren {
  AppFeedPostIdRoute: typeof AppFeedPostIdRoute
  AppFeedAdminRoute: typeof AppFeedAdminRoute
}

const AppFeedRouteChildren: AppFeedRouteChildren = {
  AppFeedPostIdRoute: AppFeedPostIdRoute,
  AppFeedAdminRoute: AppFeedAdminRoute,
}

const AppFeedRouteWithChildren =
  AppFeedRoute._addFileChildren(AppFeedRouteChildren)

interface AppNotesRouteChildren {
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppRoomsRouteChildren {
  AppRoomsMineRoute: typeof AppRoomsMineRoute
}

const AppRoomsRouteChildren: AppRoomsRouteChildren = {
  AppRoomsMineRoute: AppRoomsMineRoute,
}

const AppRoomsRouteWithChildren = AppRoomsRoute._addFileChildren(
  AppRoomsRouteChildren,
)

interface AppRouteChildren {
  AppFeedRoute: typeof AppFeedRouteWithChildren
  AppGigsRoute: typeof AppGigsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppRoomsRoute: typeof AppRoomsRouteWithChildren
  AppChatRoomIdRoute: typeof AppChatRoomIdRoute
  AppLecturesLectureIdRoute: typeof AppLecturesLectureIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFeedRoute: AppFeedRouteWithChildren,
  AppGigsRoute: AppGigsRoute,
  AppHomeRoute: AppHomeRoute,
  AppNotesRoute: AppNotesRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppRoomsRoute: AppRoomsRouteWithChildren,
  AppChatRoomIdRoute: AppChatRoomIdRoute,
  AppLecturesLectureIdRoute: AppLecturesLectureIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
