/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNoticesRouteImport } from './routes/_app.notices'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppLostFoundRouteImport } from './routes/_app.lost-found'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppGigsRouteImport } from './routes/_app.gigs'
import { Route as AppFriendsRouteImport } from './routes/_app.friends'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppChatIndexRouteImport } from './routes/_app.chat.index'
import { Route as AppRoomsMineRouteImport } from './routes/_app.rooms.mine'
import { Route as AppRoomsAdminRouteImport } from './routes/_app.rooms.admin'
import { Route as AppNoticesAdminRouteImport } from './routes/_app.notices.admin'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app.notes.$noteId'
import { Route as AppLibraryNotificationsRouteImport } from './routes/_app.library.notifications'
import { Route as AppLibraryAdminRouteImport } from './routes/_app.library.admin'
import { Route as AppLecturesAdminRouteImport } from './routes/_app.lectures.admin'
import { Route as AppLecturesLectureIdRouteImport } from './routes/_app.lectures.$lectureId'
import { Route as AppGigsOrdersRouteImport } from './routes/_app.gigs.orders'
import { Route as AppGigsNewRouteImport } from './routes/_app.gigs.new'
import { Route as AppGigsGigIdRouteImport } from './routes/_app.gigs.$gigId'
import { Route as AppFeedAdminRouteImport } from './routes/_app.feed.admin'
import { Route as AppFeedPostIdRouteImport } from './routes/_app.feed.$postId'
import { Route as AppChatRoomIdRouteImport } from './routes/_app.chat.$roomId'
import { Route as AppLibraryPeerNewRouteImport } from './routes/_app.library.peer.new'
import { Route as AppLibraryPeerListingIdRouteImport } from './routes/_app.library.peer.$listingId'
import { Route as AppLibraryBookBookIdRouteImport } from './routes/_app.library.book.$bookId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppLostFoundRoute = AppLostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsRoute = AppGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsMineRoute = AppRoomsMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => AppRoomsRoute,
} as any)
const AppRoomsAdminRoute = AppRoomsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoomsRoute,
} as any)
const AppNoticesAdminRoute = AppNoticesAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppNoticesRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppLibraryNotificationsRoute = AppLibraryNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryAdminRoute = AppLibraryAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLecturesAdminRoute = AppLecturesAdminRouteImport.update({
  id: '/lectures/admin',
  path: '/lectures/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppLecturesLectureIdRoute = AppLecturesLectureIdRouteImport.update({
  id: '/lectures/$lectureId',
  path: '/lectures/$lectureId',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsOrdersRoute = AppGigsOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppGigsRoute,
} as any)
const AppGigsNewRoute = AppGigsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppGigsRoute,
} as any)
const AppGigsGigIdRoute = AppGigsGigIdRouteImport.update({
  id: '/$gigId',
  path: '/$gigId',
  getParentRoute: () => AppGigsRoute,
} as any)
const AppFeedAdminRoute = AppFeedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppFeedRoute,
} as any)
const AppFeedPostIdRoute = AppFeedPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AppFeedRoute,
} as any)
const AppChatRoomIdRoute = AppChatRoomIdRouteImport.update({
  id: '/chat/$roomId',
  path: '/chat/$roomId',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryPeerNewRoute = AppLibraryPeerNewRouteImport.update({
  id: '/peer/new',
  path: '/peer/new',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryPeerListingIdRoute = AppLibraryPeerListingIdRouteImport.update({
  id: '/peer/$listingId',
  path: '/peer/$listingId',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryBookBookIdRoute = AppLibraryBookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => AppLibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/friends': typeof AppFriendsRoute
  '/gigs': typeof AppGigsRouteWithChildren
  '/home': typeof AppHomeRoute
  '/library': typeof AppLibraryRouteWithChildren
  '/lost-found': typeof AppLostFoundRoute
  '/notes': typeof AppNotesRouteWithChildren
  '/notices': typeof AppNoticesRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/rooms': typeof AppRoomsRouteWithChildren
  '/chat/$roomId': typeof AppChatRoomIdRoute
  '/feed/$postId': typeof AppFeedPostIdRoute
  '/feed/admin': typeof AppFeedAdminRoute
  '/gigs/$gigId': typeof AppGigsGigIdRoute
  '/gigs/new': typeof AppGigsNewRoute
  '/gigs/orders': typeof AppGigsOrdersRoute
  '/lectures/$lectureId': typeof AppLecturesLectureIdRoute
  '/lectures/admin': typeof AppLecturesAdminRoute
  '/library/admin': typeof AppLibraryAdminRoute
  '/library/notifications': typeof AppLibraryNotificationsRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/notices/admin': typeof AppNoticesAdminRoute
  '/rooms/admin': typeof AppRoomsAdminRoute
  '/rooms/mine': typeof AppRoomsMineRoute
  '/chat/': typeof AppChatIndexRoute
  '/library/book/$bookId': typeof AppLibraryBookBookIdRoute
  '/library/peer/$listingId': typeof AppLibraryPeerListingIdRoute
  '/library/peer/new': typeof AppLibraryPeerNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/friends': typeof AppFriendsRoute
  '/gigs': typeof AppGigsRouteWithChildren
  '/home': typeof AppHomeRoute
  '/library': typeof AppLibraryRouteWithChildren
  '/lost-found': typeof AppLostFoundRoute
  '/notes': typeof AppNotesRouteWithChildren
  '/notices': typeof AppNoticesRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/rooms': typeof AppRoomsRouteWithChildren
  '/chat/$roomId': typeof AppChatRoomIdRoute
  '/feed/$postId': typeof AppFeedPostIdRoute
  '/feed/admin': typeof AppFeedAdminRoute
  '/gigs/$gigId': typeof AppGigsGigIdRoute
  '/gigs/new': typeof AppGigsNewRoute
  '/gigs/orders': typeof AppGigsOrdersRoute
  '/lectures/$lectureId': typeof AppLecturesLectureIdRoute
  '/lectures/admin': typeof AppLecturesAdminRoute
  '/library/admin': typeof AppLibraryAdminRoute
  '/library/notifications': typeof AppLibraryNotificationsRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/notices/admin': typeof AppNoticesAdminRoute
  '/rooms/admin': typeof AppRoomsAdminRoute
  '/rooms/mine': typeof AppRoomsMineRoute
  '/chat': typeof AppChatIndexRoute
  '/library/book/$bookId': typeof AppLibraryBookBookIdRoute
  '/library/peer/$listingId': typeof AppLibraryPeerListingIdRoute
  '/library/peer/new': typeof AppLibraryPeerNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin-setup': typeof AdminSetupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/feed': typeof AppFeedRouteWithChildren
  '/_app/friends': typeof AppFriendsRoute
  '/_app/gigs': typeof AppGigsRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/library': typeof AppLibraryRouteWithChildren
  '/_app/lost-found': typeof AppLostFoundRoute
  '/_app/notes': typeof AppNotesRouteWithChildren
  '/_app/notices': typeof AppNoticesRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/rooms': typeof AppRoomsRouteWithChildren
  '/_app/chat/$roomId': typeof AppChatRoomIdRoute
  '/_app/feed/$postId': typeof AppFeedPostIdRoute
  '/_app/feed/admin': typeof AppFeedAdminRoute
  '/_app/gigs/$gigId': typeof AppGigsGigIdRoute
  '/_app/gigs/new': typeof AppGigsNewRoute
  '/_app/gigs/orders': typeof AppGigsOrdersRoute
  '/_app/lectures/$lectureId': typeof AppLecturesLectureIdRoute
  '/_app/lectures/admin': typeof AppLecturesAdminRoute
  '/_app/library/admin': typeof AppLibraryAdminRoute
  '/_app/library/notifications': typeof AppLibraryNotificationsRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_app/notices/admin': typeof AppNoticesAdminRoute
  '/_app/rooms/admin': typeof AppRoomsAdminRoute
  '/_app/rooms/mine': typeof AppRoomsMineRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/library/book/$bookId': typeof AppLibraryBookBookIdRoute
  '/_app/library/peer/$listingId': typeof AppLibraryPeerListingIdRoute
  '/_app/library/peer/new': typeof AppLibraryPeerNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-setup'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/feed'
    | '/friends'
    | '/gigs'
    | '/home'
    | '/library'
    | '/lost-found'
    | '/notes'
    | '/notices'
    | '/profile'
    | '/rooms'
    | '/chat/$roomId'
    | '/feed/$postId'
    | '/feed/admin'
    | '/gigs/$gigId'
    | '/gigs/new'
    | '/gigs/orders'
    | '/lectures/$lectureId'
    | '/lectures/admin'
    | '/library/admin'
    | '/library/notifications'
    | '/notes/$noteId'
    | '/notices/admin'
    | '/rooms/admin'
    | '/rooms/mine'
    | '/chat/'
    | '/library/book/$bookId'
    | '/library/peer/$listingId'
    | '/library/peer/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-setup'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/feed'
    | '/friends'
    | '/gigs'
    | '/home'
    | '/library'
    | '/lost-found'
    | '/notes'
    | '/notices'
    | '/profile'
    | '/rooms'
    | '/chat/$roomId'
    | '/feed/$postId'
    | '/feed/admin'
    | '/gigs/$gigId'
    | '/gigs/new'
    | '/gigs/orders'
    | '/lectures/$lectureId'
    | '/lectures/admin'
    | '/library/admin'
    | '/library/notifications'
    | '/notes/$noteId'
    | '/notices/admin'
    | '/rooms/admin'
    | '/rooms/mine'
    | '/chat'
    | '/library/book/$bookId'
    | '/library/peer/$listingId'
    | '/library/peer/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin-setup'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/admin'
    | '/_app/feed'
    | '/_app/friends'
    | '/_app/gigs'
    | '/_app/home'
    | '/_app/library'
    | '/_app/lost-found'
    | '/_app/notes'
    | '/_app/notices'
    | '/_app/profile'
    | '/_app/rooms'
    | '/_app/chat/$roomId'
    | '/_app/feed/$postId'
    | '/_app/feed/admin'
    | '/_app/gigs/$gigId'
    | '/_app/gigs/new'
    | '/_app/gigs/orders'
    | '/_app/lectures/$lectureId'
    | '/_app/lectures/admin'
    | '/_app/library/admin'
    | '/_app/library/notifications'
    | '/_app/notes/$noteId'
    | '/_app/notices/admin'
    | '/_app/rooms/admin'
    | '/_app/rooms/mine'
    | '/_app/chat/'
    | '/_app/library/book/$bookId'
    | '/_app/library/peer/$listingId'
    | '/_app/library/peer/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminSetupRoute: typeof AdminSetupRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lost-found': {
      id: '/_app/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof AppLostFoundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs': {
      id: '/_app/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof AppGigsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms/mine': {
      id: '/_app/rooms/mine'
      path: '/mine'
      fullPath: '/rooms/mine'
      preLoaderRoute: typeof AppRoomsMineRouteImport
      parentRoute: typeof AppRoomsRoute
    }
    '/_app/rooms/admin': {
      id: '/_app/rooms/admin'
      path: '/admin'
      fullPath: '/rooms/admin'
      preLoaderRoute: typeof AppRoomsAdminRouteImport
      parentRoute: typeof AppRoomsRoute
    }
    '/_app/notices/admin': {
      id: '/_app/notices/admin'
      path: '/admin'
      fullPath: '/notices/admin'
      preLoaderRoute: typeof AppNoticesAdminRouteImport
      parentRoute: typeof AppNoticesRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/_app/library/notifications': {
      id: '/_app/library/notifications'
      path: '/notifications'
      fullPath: '/library/notifications'
      preLoaderRoute: typeof AppLibraryNotificationsRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/_app/library/admin': {
      id: '/_app/library/admin'
      path: '/admin'
      fullPath: '/library/admin'
      preLoaderRoute: typeof AppLibraryAdminRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/_app/lectures/admin': {
      id: '/_app/lectures/admin'
      path: '/lectures/admin'
      fullPath: '/lectures/admin'
      preLoaderRoute: typeof AppLecturesAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lectures/$lectureId': {
      id: '/_app/lectures/$lectureId'
      path: '/lectures/$lectureId'
      fullPath: '/lectures/$lectureId'
      preLoaderRoute: typeof AppLecturesLectureIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs/orders': {
      id: '/_app/gigs/orders'
      path: '/orders'
      fullPath: '/gigs/orders'
      preLoaderRoute: typeof AppGigsOrdersRouteImport
      parentRoute: typeof AppGigsRoute
    }
    '/_app/gigs/new': {
      id: '/_app/gigs/new'
      path: '/new'
      fullPath: '/gigs/new'
      preLoaderRoute: typeof AppGigsNewRouteImport
      parentRoute: typeof AppGigsRoute
    }
    '/_app/gigs/$gigId': {
      id: '/_app/gigs/$gigId'
      path: '/$gigId'
      fullPath: '/gigs/$gigId'
      preLoaderRoute: typeof AppGigsGigIdRouteImport
      parentRoute: typeof AppGigsRoute
    }
    '/_app/feed/admin': {
      id: '/_app/feed/admin'
      path: '/admin'
      fullPath: '/feed/admin'
      preLoaderRoute: typeof AppFeedAdminRouteImport
      parentRoute: typeof AppFeedRoute
    }
    '/_app/feed/$postId': {
      id: '/_app/feed/$postId'
      path: '/$postId'
      fullPath: '/feed/$postId'
      preLoaderRoute: typeof AppFeedPostIdRouteImport
      parentRoute: typeof AppFeedRoute
    }
    '/_app/chat/$roomId': {
      id: '/_app/chat/$roomId'
      path: '/chat/$roomId'
      fullPath: '/chat/$roomId'
      preLoaderRoute: typeof AppChatRoomIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/peer/new': {
      id: '/_app/library/peer/new'
      path: '/peer/new'
      fullPath: '/library/peer/new'
      preLoaderRoute: typeof AppLibraryPeerNewRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/_app/library/peer/$listingId': {
      id: '/_app/library/peer/$listingId'
      path: '/peer/$listingId'
      fullPath: '/library/peer/$listingId'
      preLoaderRoute: typeof AppLibraryPeerListingIdRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/_app/library/book/$bookId': {
      id: '/_app/library/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/library/book/$bookId'
      preLoaderRoute: typeof AppLibraryBookBookIdRouteImport
      parentRoute: typeof AppLibraryRoute
    }
  }
}

interface AppFeedRouteChildren {
  AppFeedPostIdRoute: typeof AppFeedPostIdRoute
  AppFeedAdminRoute: typeof AppFeedAdminRoute
}

const AppFeedRouteChildren: AppFeedRouteChildren = {
  AppFeedPostIdRoute: AppFeedPostIdRoute,
  AppFeedAdminRoute: AppFeedAdminRoute,
}

const AppFeedRouteWithChildren =
  AppFeedRoute._addFileChildren(AppFeedRouteChildren)

interface AppGigsRouteChildren {
  AppGigsGigIdRoute: typeof AppGigsGigIdRoute
  AppGigsNewRoute: typeof AppGigsNewRoute
  AppGigsOrdersRoute: typeof AppGigsOrdersRoute
}

const AppGigsRouteChildren: AppGigsRouteChildren = {
  AppGigsGigIdRoute: AppGigsGigIdRoute,
  AppGigsNewRoute: AppGigsNewRoute,
  AppGigsOrdersRoute: AppGigsOrdersRoute,
}

const AppGigsRouteWithChildren =
  AppGigsRoute._addFileChildren(AppGigsRouteChildren)

interface AppLibraryRouteChildren {
  AppLibraryAdminRoute: typeof AppLibraryAdminRoute
  AppLibraryNotificationsRoute: typeof AppLibraryNotificationsRoute
  AppLibraryBookBookIdRoute: typeof AppLibraryBookBookIdRoute
  AppLibraryPeerListingIdRoute: typeof AppLibraryPeerListingIdRoute
  AppLibraryPeerNewRoute: typeof AppLibraryPeerNewRoute
}

const AppLibraryRouteChildren: AppLibraryRouteChildren = {
  AppLibraryAdminRoute: AppLibraryAdminRoute,
  AppLibraryNotificationsRoute: AppLibraryNotificationsRoute,
  AppLibraryBookBookIdRoute: AppLibraryBookBookIdRoute,
  AppLibraryPeerListingIdRoute: AppLibraryPeerListingIdRoute,
  AppLibraryPeerNewRoute: AppLibraryPeerNewRoute,
}

const AppLibraryRouteWithChildren = AppLibraryRoute._addFileChildren(
  AppLibraryRouteChildren,
)

interface AppNotesRouteChildren {
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppNoticesRouteChildren {
  AppNoticesAdminRoute: typeof AppNoticesAdminRoute
}

const AppNoticesRouteChildren: AppNoticesRouteChildren = {
  AppNoticesAdminRoute: AppNoticesAdminRoute,
}

const AppNoticesRouteWithChildren = AppNoticesRoute._addFileChildren(
  AppNoticesRouteChildren,
)

interface AppRoomsRouteChildren {
  AppRoomsAdminRoute: typeof AppRoomsAdminRoute
  AppRoomsMineRoute: typeof AppRoomsMineRoute
}

const AppRoomsRouteChildren: AppRoomsRouteChildren = {
  AppRoomsAdminRoute: AppRoomsAdminRoute,
  AppRoomsMineRoute: AppRoomsMineRoute,
}

const AppRoomsRouteWithChildren = AppRoomsRoute._addFileChildren(
  AppRoomsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppFeedRoute: typeof AppFeedRouteWithChildren
  AppFriendsRoute: typeof AppFriendsRoute
  AppGigsRoute: typeof AppGigsRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppLibraryRoute: typeof AppLibraryRouteWithChildren
  AppLostFoundRoute: typeof AppLostFoundRoute
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppNoticesRoute: typeof AppNoticesRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppRoomsRoute: typeof AppRoomsRouteWithChildren
  AppChatRoomIdRoute: typeof AppChatRoomIdRoute
  AppLecturesLectureIdRoute: typeof AppLecturesLectureIdRoute
  AppLecturesAdminRoute: typeof AppLecturesAdminRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppFeedRoute: AppFeedRouteWithChildren,
  AppFriendsRoute: AppFriendsRoute,
  AppGigsRoute: AppGigsRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppLibraryRoute: AppLibraryRouteWithChildren,
  AppLostFoundRoute: AppLostFoundRoute,
  AppNotesRoute: AppNotesRouteWithChildren,
  AppNoticesRoute: AppNoticesRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppRoomsRoute: AppRoomsRouteWithChildren,
  AppChatRoomIdRoute: AppChatRoomIdRoute,
  AppLecturesLectureIdRoute: AppLecturesLectureIdRoute,
  AppLecturesAdminRoute: AppLecturesAdminRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminSetupRoute: AdminSetupRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
